id: PBE4494F3
initial_creation_type: input
source_metadata:
  Title: Tattvaratnāvalī
  Editor: H. UI
  Publisher: '-'
  Place of Publication: '-'
  Year: '1963'
  तत्त्वरत्नावली:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:11:52.545039'
last_modified_at: '2022-03-08T17:11:52.545047'
